name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/*.py'
      - 'docs/*.rst'
      - 'src/**'
      - 'tests/**'
      - '*.nimble'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        nim-version:
          - '1.6.0'
    steps:
      - uses: actions/checkout@v2
      - name: Cache Nim resources
        id: cache_nim
        uses: actions/cache@v2
        with:
          path: |
            ~/.choosenim
            ~/.nimble
          key: nimcaches--${{ matrix.os }}-${{ matrix.nim-version }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: |
          nimble build -Y
          nimble test -Y
  doctest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: |
          pip install Sphinx
          make -C docs html
          make -C docs man
