name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.nimble'
      - '*.nims'
    tags-ignore:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        nim-version:
          - '1.6.0'
    steps:
      - uses: actions/checkout@v1
      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ matrix.os }}-choosenim-${{ matrix.nim-version }}
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: nimble-${{ matrix.os }}-${{ matrix.nim-version }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: |
          nimble build -Y
          nimble test -Y
